%YAML:1.0
aruco_bc_nmarkers: 1
aruco_bc_mInfoType: 0 # NONE=-1,PIX=0,METERS=1
aruco_bc_markers:
   - { id:152, corners:[ [ -110., -110., 0. ], [ -10., -110., 0. ], [
       -10., -10., 0. ], [ -110., -10., 0. ] ] }

